<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

	/*
		This seeder is for temporary use. This data must come from the .csv file.
	*/

class SectionTableSeeder extends Seeder {
	
	public function run()
	{
		DB::table('sections')->delete();				//delete whatever data is present before adding new ones
		
		DB::table('sections')->insert(array(
			
			['sid'=>'cmsc2e',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 2',
			'sectionNum'=>'E',
			'startTime'=>'1:00',
			'endTime'=>'2:00',
			'day'=>'W/F',
			'roomNum'=>'ICS MH',
			'employeeId'=>'111',
			'classSize'=>'97',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc2e1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 2',
			'sectionNum'=>'E-1L',
			'startTime'=>'10:00',
			'endTime'=>'1:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 2',
			'employeeId'=>'111',
			'classSize'=>'14',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc2e2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 2',
			'sectionNum'=>'E-2L',
			'startTime'=>'4:00',
			'endTime'=>'7:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 2',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc2e3l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 2',
			'sectionNum'=>'E-3L',
			'startTime'=>'10:00',
			'endTime'=>'1:00',
			'day'=>'W',
			'roomNum'=>'PC LAB 2',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc2e4l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 2',
			'sectionNum'=>'E-4L',
			'startTime'=>'10:00',
			'endTime'=>'1:00',
			'day'=>'TH',
			'roomNum'=>'PC LAB 2',
			'employeeId'=>'111',
			'classSize'=>'23',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc11t',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'T',
			'startTime'=>'9:00',
			'endTime'=>'10:00',
			'day'=>'T/TH',
			'roomNum'=>'ICS MH',
			'employeeId'=>'111',
			'classSize'=>'92',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc11t1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'T-1L',
			'startTime'=>'10:00',
			'endTime'=>'1:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 3',
			'employeeId'=>'111',
			'classSize'=>'16',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc11t2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'T-2L',
			'startTime'=>'4:00',
			'endTime'=>'7:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 3',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc11u',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'U',
			'startTime'=>'10:00',
			'endTime'=>'11:00',
			'day'=>'T/TH',
			'roomNum'=>'ICS MH',
			'employeeId'=>'111',
			'classSize'=>'107',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc11u1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'U-1L',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 3',
			'employeeId'=>'111',
			'classSize'=>'20',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc11u2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 11',
			'sectionNum'=>'U-2L',
			'startTime'=>'10:00',
			'endTime'=>'1:00',
			'day'=>'W',
			'roomNum'=>'PC LAB 3',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],

			['sid'=>'cmsc21st',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 21',
			'sectionNum'=>'ST',
			'startTime'=>'8:00',
			'endTime'=>'9:00',
			'day'=>'T/TH',
			'roomNum'=>'ICS MH',
			'employeeId'=>'111',
			'classSize'=>'111',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc21st1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 21',
			'sectionNum'=>'ST-1L',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 4',
			'employeeId'=>'111',
			'classSize'=>'16',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc21st2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 21',
			'sectionNum'=>'ST-2L',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'W',
			'roomNum'=>'PC LAB 2',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc141d',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 141',
			'sectionNum'=>'D',
			'startTime'=>'12:00',
			'endTime'=>'1:00',
			'day'=>'W/F',
			'roomNum'=>'ICS MH',
			'employeeId'=>'111',
			'classSize'=>'141',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc141d1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 141',
			'sectionNum'=>'D-1L',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'M',
			'roomNum'=>'PC LAB 8',
			'employeeId'=>'111',
			'classSize'=>'20',
			'teachingUnits'=>1.5],
			
			['sid'=>'cmsc141d2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 141',
			'sectionNum'=>'D-2L',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'T',
			'roomNum'=>'PC LAB 8',
			'employeeId'=>'111',
			'classSize'=>'22',
			'teachingUnits'=>1.5],

			['sid'=>'cmsc200ar1',
			'type'=>'Sect',
			'courseNum'=>'CMSC 200',
			'sectionNum'=>'AR1',
			'startTime'=>'TBA',
			'endTime'=>'TBA',
			'day'=>'M',
			'roomNum'=>'TBA',
			'employeeId'=>'111',
			'classSize'=>'1',
			'teachingUnits'=>0.0],
			
			['sid'=>'cmsc200ar2',
			'type'=>'Sect',
			'courseNum'=>'CMSC 200',
			'sectionNum'=>'AR2',
			'startTime'=>'TBA',
			'endTime'=>'TBA',
			'day'=>'M',
			'roomNum'=>'TBA',
			'employeeId'=>'111',
			'classSize'=>'20',
			'teachingUnits'=>0.0],

			['sid'=>'cmsc215y',
			'type'=>'Sect',
			'courseNum'=>'CMSC 215',
			'sectionNum'=>'Y',
			'startTime'=>'4:00',
			'endTime'=>'7:00',
			'day'=>'T',
			'roomNum'=>'ICS LH 3',
			'employeeId'=>'111',
			'classSize'=>'19',
			'teachingUnits'=>4.5],
			
			['sid'=>'cmsc227wx',
			'type'=>'Sect',
			'courseNum'=>'CMSC 227',
			'sectionNum'=>'WX',
			'startTime'=>'1:00',
			'endTime'=>'4:00',
			'day'=>'T',
			'roomNum'=>'ICS GS Room',
			'employeeId'=>'111',
			'classSize'=>'13',
			'teachingUnits'=>4.5],

			['sid'=>'cmsc210ef',
			'type'=>'Lecture',
			'courseNum'=>'CMSC 210',
			'sectionNum'=>'EF',
			'startTime'=>'2:00',
			'endTime'=>'4:00',
			'day'=>'M/F',
			'roomNum'=>'ICS GS Room',
			'employeeId'=>'111',
			'classSize'=>'13',
			'teachingUnits'=>3.0],
			
			['sid'=>'cmsc210ef1l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 210',
			'sectionNum'=>'EF-1L',
			'startTime'=>'4:00',
			'endTime'=>'7:00',
			'day'=>'M',
			'roomNum'=>'PC LAB 6',
			'employeeId'=>'111',
			'classSize'=>'13',
			'teachingUnits'=>2.25],
	
			['sid'=>'cmsc210ef2l',
			'type'=>'Lab',
			'courseNum'=>'CMSC 210',
			'sectionNum'=>'EF-2L',
			'startTime'=>'4:00',
			'endTime'=>'7:00',
			'day'=>'F',
			'roomNum'=>'PC LAB 1',
			'employeeId'=>'111',
			'classSize'=>'13',
			'teachingUnits'=>2.25],

			['sid'=>'cmsc400ar1',
			'type'=>'Sect',
			'courseNum'=>'CMSC 400',
			'sectionNum'=>'AR1',
			'startTime'=>'TBA',
			'endTime'=>'TBA',
			'day'=>'TBA',
			'roomNum'=>'TBA',
			'employeeId'=>'111',
			'classSize'=>'3',
			'teachingUnits'=>0.0],

		));
	}
}
